#
# This file contains configuration flags to customize your site
#

# Specify Your SEO Title | Pro Tip! - Use Synonyms & 60â€“70 characters 

title: Discover Top VPNs - Our Recommended Services for Living in China

# Description | Recommended - 110-235 characters

description: test


# Search Engine Indexing | Set "false" to Allow  
# Long Term Noindex Will Lead To Nofollow On Links

noindex: true

# Meta Tags

# Opengraph Settings

# Set "og:site-name" to activate your og meta tags
og_site-name: og test title
# Choose a custom locale or leave empty for default "en_US"
og_locale: 
# Image is only displayed if no page.featured-image is set
og_img: 
og_img-width: 
og_img-height: 

# Twitter Cards | Insert Image URL to Enable

tc: summary
tc_img: https://yourimgurl.com/image.png

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://raw.githubusercontent.com/mindpower4/blog/master/images/logo.png

#
# Flags below are optional
#

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email: 
  facebook:
  flickr:
  github: 
  instagram: 
  linkedin: 
  pinterest:
  rss: # type anything here for a working RSS icon
  twitter: test
  stackoverflow: # your stackoverflow profile, e.g. "users/33333/jack-norris"
  youtube: # channel/<your_long_string> or user/<user-name>


# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus:

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics:

# Your website URL (e.g. https://socialvypr.github.io or https://socialvypr.com)
# Used for Sitemap.xml and your RSS feed
url: https://bestchinavpn.org

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

#
# ! Advanced Settings
#

permalink: /:title/

# The release of seovly that you're using
version: v1.0.1

# Jekyll Kramdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to use :expanded

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
